

-- CRIAR A TABELA MÃE
CREATE TABLE [MÃE]
([CPF] VARCHAR(11) NOT NULL,
 [NOME] VARCHAR(150) NOT NULL,
 [ENDEREÇO] VARCHAR(200) NULL,
 [TELEFONE] VARCHAR(15) NULL,
 
 -- CHAVE PRIMARIA
 CONSTRAINT [PK MÃE]
	PRIMARY KEY([CPF]))

	ALTER TABLE [MÃE] ADD [DATA NASCIMENTO] DATE NULL

-- TABELA BEBÊ
CREATE TABLE [BEBÊ]
([NOME] VARCHAR(150) NOT NULL,
 [DATA NASCIMENTO] DATE NOT NULL,
 [PESO] NUMERIC(8, 0) NULL,
 [ALTURA] NUMERIC(8, 0) NULL)

-- ALTER TABLE(ADD ATRIBUTOS, MUDAR NOMES, ETC)
-- ADD UMA NOVA COLUNA CHAVE PRIMARIA
ALTER TABLE [BEBÊ] ADD [NRO REG] INT NOT NULL PRIMARY KEY IDENTITY(1,1)
-- ADD RELAÇÃO MÃE E BEBÊ
ALTER TABLE [BEBÊ] ADD [CPF MÃE] VARCHAR(11) NOT NULL 

ALTER TABLE [BEBÊ] WITH CHECK ADD CONSTRAINT [FK MÃE]
FOREIGN KEY([CPF MÃE]) REFERENCES [MÃE]([CPF])

-- TABELA MÉDICO
CREATE TABLE [MÉDICO]
([CRM] VARCHAR(6) NOT NULL,
 [NOME] VARCHAR(150) NOT NULL,
 [TELEFONE] VARCHAR(15) NULL,
 [ESPECIALIDADE] VARCHAR(100) NULL,
 -- CHAVE PRIMARIA
 CONSTRAINT [PK MÉDICO]
	PRIMARY KEY CLUSTERED ([CRM]))

-- RELACIONAMENTO N:N BEBÊ E MÉDICO
CREATE TABLE [MÉDICO REALIZOU PARTO]
([CRM] VARCHAR(6) NOT NULL,
 [NRO REG] INT NOT NULL,
 [NOME MÉDICO] VARCHAR(150) NULL,
 [NOME BEBÊ] VARCHAR(150) NULL,
 CONSTRAINT [FK CRM]
	FOREIGN KEY ([CRM]) REFERENCES [MÉDICO]([CRM]),
 CONSTRAINT [FK NRO REG]
	FOREIGN KEY ([NRO REG]) REFERENCES [BEBÊ]([NRO REG]))

	--([CRM],[NOME MÉDICO], [NRO REG], [NOME BEBÊ])
------------------------- ------------------------------------------------

-- INSERTS DAS MÃES
INSERT INTO [MÃE]
([CPF], [DATA NASCIMENTO], [ENDEREÇO], [NOME], [TELEFONE])
VALUES
('1547862', '1990-04-13', 'Rua: 1 São Francisco', 'Carolina', '(16)98562-5642')

INSERT INTO [MÃE]
([CPF], [DATA NASCIMENTO], [ENDEREÇO], [NOME], [TELEFONE])
VALUES
('1235698', '1900-07-22', 'Rua das Olindas', 'Roberta', '(21)94758-1452')

INSERT INTO [MÃE]
([CPF], [DATA NASCIMENTO], [ENDEREÇO], [NOME], [TELEFONE])
VALUES
('3586923', '1991-06-05', 'Rua 7 Jardim das Rosas', 'Mariana', '(17)97125-4862')

INSERT INTO [MÃE]
([CPF], [DATA NASCIMENTO], [ENDEREÇO], [NOME], [TELEFONE])
VALUES
('857463', '2000-12-29', 'Av: Americana', 'Sonia', '(11)94521-7432')

SELECT* 
FROM MÃE
------------------------------------------------------------------------------
-- INSERT DOS BEBÊS

INSERT INTO [BEBÊ]
([CPF MÃE], [ALTURA], [DATA NASCIMENTO], [NOME], [PESO])
VALUES
('1547862', 50, '2021-08-17', 'Otávio', 2300)

INSERT INTO [BEBÊ]
([CPF MÃE], [ALTURA], [DATA NASCIMENTO], [NOME], [PESO])
VALUES
('1235698', 47, '2021-02-01', 'Cintia', 2978)

INSERT INTO [BEBÊ]
([CPF MÃE], [ALTURA], [DATA NASCIMENTO], [NOME], [PESO])
VALUES
('857463', 51, '2020-12-11', 'Marcos', 3210)

INSERT INTO [BEBÊ]
([CPF MÃE], [ALTURA], [DATA NASCIMENTO], [NOME], [PESO])
VALUES
('857463', 47, '2020-12-11', 'Carlos', 2980)

SELECT* 
FROM BEBÊ
------------------------------------------------------------------------
-- INSERT MÉDICOS
INSERT INTO [MÉDICO]
([CRM], [NOME], [TELEFONE], [ESPECIALIDADE])
VALUES
('20586', 'João Cunha', '(16)98532-4578', 'Pediatra'),
('78451', 'Amélia Silva', '(21)99475-1245', 'Obstetra'),
('41523', 'Cátia Fernandes', '(17)99745-1123', 'Obstetra');


SELECT* 
FROM [MÉDICO REALIZOU PARTO]

SELECT CRM
FROM MÉDICO

INSERT INTO [MÉDICO REALIZOU PARTO]
([CRM],[NOME MÉDICO], [NRO REG], [NOME BEBÊ])
VALUES
('20856','João Cunha',1,'Otávio')


SELECT [CRM]
FROM [MÉDICO REALIZOU PARTO]

DECLARE @CRM VARCHAR(6)
SET @CRM = (SELECT [CRM] FROM [MÉDICO] WHERE [NOME] = 'Cátia Fernandes')
PRINT @CRM


INSERT INTO [MÉDICO REALIZOU PARTO]
([CRM], [NOME MÉDICO], [NRO REG], [NOME BEBÊ])
VALUES
(@CRM,'Cátia Fernandes', @NRO, 'Cintia')


/*
INSERT INTO [MÉDICO REALIZOU PARTO]
([CRM], [NOME MÉDICO], [NRO REG], [NOME MÉDICO])
VALUES
(
	(SELECT [CRM] FROM [MÉDICO] WHERE [NOME] = 'Amélia Silva'),
	'Amélia Silva',
	(SELECT [NRO REG] FROM [BEBÊ] WHERE [NOME]= 'Marcos'),
	'Marcos'
)
*/

insert into [MÉDICO REALIZOU PARTO]
([CRM], [NOME MÉDICO], [NRO REG], [NOME BEBÊ])
VALUES
('78451', 'Amélia Silva', 3, 'Marcos'),
('78451', 'Amélia Silva', 4, 'Carlos');

SELECT * 
FROM [BEBÊ]
--UPDATE [TABELA] SET [ATRIBUTO] WHERE (CONDIÇÃO)
UPDATE [BEBÊ] SET [PESO] = [PESO] * 1.20	--[PESO] = [PESO] + [PESO] * 20/100
											--[PESO] * (1 + 0.2)
UPDATE [BEBÊ] SET [NOME] = 'Martins'
UPDATE [BEBÊ] SET [NOME] = 'Otávio' WHERE [NRO REG] = 1
UPDATE [BEBÊ] SET [NOME] = 'Cintia' WHERE [NRO REG] = 2
UPDATE [BEBÊ] SET [NOME] = 'Marcos' WHERE [NRO REG] = 3
UPDATE [BEBÊ] SET [NOME] = 'Carlos' WHERE [NRO REG] = 4

-- DELETE
-- DELETE FROM [TABELA] WHERE (CONDIÇÃO)
DELETE FROM [MÃE] WHERE [CPF] = '011533'

SELECT * FROM [MÉDICO REALIZOU PARTO]

SELECT [NOME MÉDICO], [NOME BEBÊ] FROM [MÉDICO REALIZOU PARTO]


SELECT [CPF MÃE] FROM [BEBÊ]
SELECT DISTINCT [CPF MÃE] FROM [BEBÊ]
SELECT DISTINCT [CPF MÃE], [NOME] FROM [BEBÊ]



SELECT * FROM [BEBÊ]
ORDER BY [NOME]

SELECT * FROM [BEBÊ]
ORDER BY [NOME] ASC

SELECT * FROM [BEBÊ]
ORDER BY [NOME] DESC

--------------------------------------------
-- AGREGAÇÃO
--SOMA DE TODOS OS PESOS DOS BEBÊS

SELECT SUM([PESO]) AS [SOMA DE TODOS OS BABY], SUM([ALTURA]) AS [ALTURA] FROM [BEBÊ] 

SELECT [CPF MÃE], AVG([ALTURA]) AS [MÉDIA DAS ALTURAS] FROM [BEBÊ] GROUP BY [CPF MÃE]

SELECT [CPF MÃE], COUNT(*) FROM [BEBÊ] GROUP BY [CPF MÃE]
